# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSDK.Model.Response do
  @moduledoc """

  """
  alias RasaSDK.Model.Button

  @derive [Poison.Encoder]
  defstruct [
    :text,
    :template,
    :buttons
  ]

  @type t :: %__MODULE__{
          text: String.t(),
          template: String.t(),
          buttons: [Button] | nil
        }
end

defimpl Poison.Decoder, for: RasaSDK.Model.Response do
  import RasaSDK.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:buttons, :list, RasaSDK.Model.Button, options)
  end
end
