# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSDK.Model.ResponseOk do
  @moduledoc """
  Action was executed succesfully.
  """
  alias RasaSDK.Model.Event
  alias RasaSDK.Model.Response

  @derive [Poison.Encoder]
  defstruct [
    :events,
    :responses
  ]

  @type t :: %__MODULE__{
          events: [Event] | nil,
          responses: [Response] | nil
        }
end

defimpl Poison.Decoder, for: RasaSDK.Model.ResponseOk do
  import RasaSDK.Deserializer

  def decode(value, options) do
    value
    |> deserialize(:events, :list, RasaSDK.Model.Event, options)
    |> deserialize(:responses, :list, RasaSDK.Model.Response, options)
  end
end
