# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSdk.Model.TemplateResponse do
  @moduledoc """
  Response template the bot should utter.
  """

  @derive [Jason.Encoder]
  defstruct [
    :template
  ]

  @type t :: %__MODULE__{
    template: String.t
  }
end

defimpl Jason.Decoder, for: RasaSdk.Model.TemplateResponse do
  def decode(value, _options) do
    value
  end
end

