# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSDK.Model.TrackerActiveForm do
  @moduledoc """
  Name of the active form
  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :validate
  ]

  @type t :: %__MODULE__{
          name: String.t() | nil,
          validate: boolean() | nil
        }
end

defimpl Poison.Decoder, for: RasaSDK.Model.TrackerActiveForm do
  def decode(value, _options) do
    value
  end
end
